### PR TITLE
Add path validation of arguments

### PR DESCRIPTION
**Pull request by MadeOfMagicAndWires**
Implements #4 by resolving the given `path` parameter to an absolute path and checking whether that resides in `PAGES_BASE_DIR`, exiting if it does not or if the resolved path does not exist.

Additionally, it no longer pre/appends the `PAGES_BASE_DIR` or `PAGES_FILE_EXT` to path if it is already provided, allowing users to provide full paths  as arguments (as long as the resolved path resides in the base directory). 
Thus: 
+ `$ shortcut vim`, 
+ `$ shortcut vim.md`, 
+ `$ shortcut /opt/shortcut/pages/vim`,
+ `$ shortcut  /opt/shortcut/pages/vim.md` 

All resolve successfully. 
A fairly useless addition, but I kept accidentally inserting full paths and getting confused when it couldn't find any shortcuts.

The main downside of this addition is that the usage of `realpath()` is part of the POSIX standard, so **any machine that isn't POSIX compliant would not be able to use this any more**. 
Should this be a concern we would have to create a realpath alternative.

### CODE REVIEW

**Comment by MadeOfMagicAndWires** [comment]
This is the first time I've really worked with feature test macro's (`_DEFAULT_SOURCE`).

 I'm fairly sure I did it right? This is how the man page seems to describe it, but I haven't been able to find very clear practical examples of them. It seems to compile with the `std=c99` flag at least, but I don't have any non-POSIX systems to test it with.

Also working on a different branch in which checks for POSIX compliance, rather than enforcing it. The difference would be that you'd either have a version which makes sure the program always has all functionality enabled, and makes sure the system is able to support it (which is this version), or a version that skips this feature when it is not supported.

I'll leave it up to you which branch you would prefer.

**Comment by MadeOfMagicAndWires** [comment]
The optional path validation branch can be found at [MadeOfMagicAndWires:check-path-opt](MadeOfMagicAndWires/shortcut-c-client/tree/check-path-opt).

Difference can be tested by passing the `-std=c99` CFLAG, which disables POSIX functionality. The `check-path` branch should try to enforce POSIX compliance regardless (and throw an error on systems without POSIX functionality) whilst `check-path-opt` will simply compile without the path validation functionality. 

(`check-path-opt` still allows full paths as arguments, but does not check whether relative paths reside in `PAGES_BASE_DIR`)

**Comment by mt-empty** [comment]
Thank you for your PR. Tested it, it looks good.

I think I will merge this PR, I don't want to deal with non-POSIX systems, at least not at this stage.


I won't have much time to maintain this repo in the next few months.
If you want, I can add you as a collaborator?

**Comment by MadeOfMagicAndWires** [comment]
@mt-empty I won't have as much time these days either but I'm up for it! It's an interesting project and a good way to refresh my C skills ;)

**Pull request merged**
